fix(tests): ensure wrapped method is set only if it exists
Fixes ERROR: tearDownClass (admin_views.test_skip_link_to_content.PlaywrightTests)
AttributeError: 'function' object has no attribute 'wrapped'

Thanks https://www.github.com/django/django/pull/20758
https://www.github.com/graphql-python/graphene-django/issues/828
(ref https://code.djangoproject.com/ticket/36942)